<?php

use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// ========================================================================
// YOUR PUBLIC AND ADMIN ROUTES ARE MERGED HERE
// ========================================================================

// 1. Your Frontend Route for the homepage
Route::get('/', [FrontendController::class, 'index'])->name('frontend.index');

// 2. Your Admin Panel Routes for Templates (now protected by auth middleware)
Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::resource('templates', TemplateController::class);
});


// ========================================================================
// ROUTES GENERATED BY LARAVEL BREEZE
// ========================================================================

// Admin Dashboard Route (Requires Login)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Profile routes generated by Breeze
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Include the auth routes generated by Breeze
require __DIR__.'/auth.php';

