@extends('app.layouts.app')

@section('content')
    <!-- Breadcrumb -->
    <section class="breadcrumb-section">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="index.html#templates">Templates</a></li>
                    <li class="breadcrumb-item active" id="breadcrumbCategory">Loading...</li>
                    <li class="breadcrumb-item active" id="breadcrumbTitle">Loading...</li>
                </ol>
            </nav>
        </div>
    </section>

    <!-- Template Detail Section -->
    <section class="detail-section">
        <div class="container">
            <div class="row g-4">
                <!-- Left Side - Preview -->
                <div class="col-lg-6">
                    <div class="preview-container sticky-top">
                        <!-- Main Preview -->
                        <div class="main-preview">
                            <div class="phone-frame">
                                <div class="phone-notch"></div>
                                <div class="phone-screen">
                                    <img id="mainPreviewImage" src="" alt="Preview" class="img-fluid">
                                </div>
                            </div>
                        </div>
                        
                        <!-- Thumbnail Gallery -->
                        <div class="thumbnail-gallery mt-4">
                            <h6 class="mb-3 fw-semibold">Preview Lainnya</h6>
                            <div class="row g-2" id="thumbnailGallery">
                                <!-- Thumbnails will be generated by JS -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right Side - Details -->
                <div class="col-lg-6">
                    <div class="detail-content">
                        <!-- Badge -->
                        <div class="mb-3" id="badgeContainer"></div>
                        
                        <!-- Title -->
                        <h1 class="detail-title mb-3" id="templateTitle">Loading...</h1>
                        
                        <!-- Rating & Reviews -->
                        <div class="rating-section mb-3">
                            <div class="stars">
                                <i class="bi bi-star-fill"></i>
                                <i class="bi bi-star-fill"></i>
                                <i class="bi bi-star-fill"></i>
                                <i class="bi bi-star-fill"></i>
                                <i class="bi bi-star-half"></i>
                            </div>
                            <span class="ms-2 text-muted">4.8 (127 ulasan)</span>
                        </div>
                        
                        <!-- Price -->
                        <div class="price-section mb-4">
                            <div class="current-price" id="templatePrice">Rp 0</div>
                            <span class="text-muted small">Harga sudah termasuk revisi minor</span>
                        </div>
                        
                        <!-- Description -->
                        <div class="description-section mb-4">
                            <h5 class="fw-semibold mb-3">Deskripsi Template</h5>
                            <p id="templateDescription" class="text-muted">Loading...</p>
                        </div>
                        
                        <!-- Features List -->
                        <div class="features-list mb-4">
                            <h5 class="fw-semibold mb-3">Fitur Yang Didapatkan</h5>
                            <ul class="feature-items">
                                <li><i class="bi bi-check-circle-fill text-success"></i> Custom Nama & Foto</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> Musik Latar Pilihan</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> Galeri Foto</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> Google Maps Lokasi</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> Countdown Timer</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> RSVP Online</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> Buku Tamu Digital</li>
                                <li><i class="bi bi-check-circle-fill text-success"></i> Share ke Social Media</li>
                            </ul>
                        </div>
                        
                        <!-- Specifications -->
                        <div class="specifications mb-4">
                            <h5 class="fw-semibold mb-3">Spesifikasi</h5>
                            <div class="row g-3">
                                <div class="col-6">
                                    <div class="spec-item">
                                        <i class="bi bi-phone text-primary"></i>
                                        <div>
                                            <div class="spec-label">Platform</div>
                                            <div class="spec-value">Mobile & Desktop</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="spec-item">
                                        <i class="bi bi-clock text-primary"></i>
                                        <div>
                                            <div class="spec-label">Waktu Pengerjaan</div>
                                            <div class="spec-value">1-2 Hari</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="spec-item">
                                        <i class="bi bi-arrow-repeat text-primary"></i>
                                        <div>
                                            <div class="spec-label">Revisi</div>
                                            <div class="spec-value">2x Gratis</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="spec-item">
                                        <i class="bi bi-infinity text-primary"></i>
                                        <div>
                                            <div class="spec-label">Masa Aktif</div>
                                            <div class="spec-value">Selamanya</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Action Buttons -->
                        <div class="action-buttons">
                            <button class="btn btn-primary btn-lg w-100 mb-3" id="orderButton">
                                <i class="bi bi-whatsapp me-2"></i>Pesan Template Ini
                            </button>
                            <button class="btn btn-outline-primary btn-lg w-100" id="demoButton">
                                <i class="bi bi-eye me-2"></i>Lihat Demo Live
                            </button>
                        </div>
                        
                        <!-- Info Box -->
                        <div class="info-box mt-4">
                            <i class="bi bi-info-circle"></i>
                            <div>
                                <strong>Butuh Bantuan?</strong>
                                <p class="mb-0">Tim kami siap membantu Anda 24/7. Hubungi kami untuk konsultasi gratis!</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Related Templates Section -->
    <section class="related-section">
        <div class="container">
            <h2 class="section-title text-center mb-5">Template Serupa</h2>
            <div class="row g-4" id="relatedTemplates">
                <!-- Related templates will be generated by JS -->
            </div>
        </div>
    </section>

    <!-- Reviews Section -->
    <section class="reviews-section">
        <div class="container">
            <h2 class="section-title text-center mb-5">Ulasan Pelanggan</h2>
            <div class="row g-4">
                <div class="col-md-6 col-lg-4">
                    <div class="review-card">
                        <div class="review-header">
                            <div class="reviewer-avatar">AS</div>
                            <div>
                                <div class="reviewer-name">Andi Saputra</div>
                                <div class="review-stars">
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                </div>
                            </div>
                        </div>
                        <p class="review-text">"Undangannya bagus banget! Tamu-tamu pada bilang keren. Pelayanan juga cepat dan ramah. Recommend!"</p>
                        <div class="review-date">2 minggu yang lalu</div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="review-card">
                        <div class="review-header">
                            <div class="reviewer-avatar">RD</div>
                            <div>
                                <div class="reviewer-name">Rina Dewi</div>
                                <div class="review-stars">
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                </div>
                            </div>
                        </div>
                        <p class="review-text">"Sangat puas dengan hasilnya. Desainnya elegan dan sesuai dengan tema pernikahan kami. Terima kasih!"</p>
                        <div class="review-date">1 bulan yang lalu</div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="review-card">
                        <div class="review-header">
                            <div class="reviewer-avatar">BP</div>
                            <div>
                                <div class="reviewer-name">Budi Pratama</div>
                                <div class="review-stars">
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-half"></i>
                                </div>
                            </div>
                        </div>
                        <p class="review-text">"Harga terjangkau dengan kualitas premium. Proses pembuatan cepat, dalam 1 hari sudah jadi. Mantap!"</p>
                        <div class="review-date">3 minggu yang lalu</div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection